name: Deploy to Firebase

on:
  pull_request:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build:prod

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase Hosting
      run: firebase deploy --token "${FIREBASE_TOKEN}"
      env:
       FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
