name: Deploy to Firebase

on:
  pull_request:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build:prod

    - name: Deploy to Firebase
      run: |
        npm install -g firebase-tools
        echo ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} > ./service-account.json
        firebase deploy --only hosting
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
